const notRawData = [
"sjdivfriyaaqaXXd2v$$k$$mpcu$$yyu$$en"                                   ,
"vcqc"                                                                   ,
"zbcwgmbpijcxu$$yins$$sfxn"                                              ,
"yumngprx"                                                               ,
"bbdj"                                                                   ,
"czbggabkzo$$wsnw$$voklp$$s"                                             ,
"acwt"                                                                   ,
"aqttwnsohbzian$$evtllfxwkog$$cunzw"                                     ,
"ugvsgfv"                                                                ,
"xlnillibxg"                                                             ,
"kexh$$pmi"                                                              ,
"syvugow"                                                                ,
"m$$ktqnw"                                                               ,
"yrbajyndte@@rm"                                                         ,
"f$$kakXX70snXXc4kjri"                                                   ,
"yxthr"                                                                  ,
"alvumfsjni$$kohg"                                                       ,
"trajsXX5bromXXf1yoijaumkem$$$$tahlzs"                                   ,
"$$oedr$$pwdbnnrc"                                                       ,
"qsmzhnx$$"                                                              ,
"$$msoytqimx@@tbklqz"                                                    ,
"mjdfcgwdshrehgs"                                                        ,
"$$rivyxahf$$"                                                           ,
"ciagcXX04bp"                                                            ,
"xkfc"                                                                   ,
"xrgcripduXX4cXXc4gszjhrvumvz$$mngbirb"                                  ,
"gvmae$$yiiujoqvr$$mkxmgbbut$$u"                                         ,
"ih"                                                                     ,
"ncrqlejehs"                                                             ,
"mknoXX43pcfdukmemycp"                                                   ,
"uanzoqxkpsksbvdnkji$$feamp"                                             ,
"axoufpnbx@@aoXX61pfj$$b"                                                ,
"dz@@ztawzdjy"                                                           ,
"ihne$$enumvswypgf"                                                      ,
"$$dgazthrphbshdo@@vuqoiy$$"                                             ,
"dlnmptzt@@zahwpylc@@b$$gmslrqysk"                                       ,
"mhxznyzcp"                                                              ,
"rebr$$amvxwXX5fmbnfpkkeghlntavj"                                        ,
"ladesXX47ncgdof$$$$jmbbk"                                               ,
"dwxuisXXa5wdkx@@z$$admgnoddpgkt@@zs"                                    ,
"g@@kXX27qslXX34hwfglcdxqbecltXXca@@"                                    ,
"lhyjky@@m$$pvnm@@xmynpxnlhndmahjl"                                      ,
"c$$uxabbgorrpprw$$xas@@vefkxioqpt"                                      ,
"rfrvjxpevcmmaXX71gtfipo"                                                ,
"fgh$$kcwoqwfnjgdlzfclprg$$q"                                            ,
"onxnwykrba"                                                             ,
"hkkgXX60f$$tjzsanpvarzgkfipl"                                           ,
"$$aintes$$ofq$$juiaqlqxmvpe@@a"                                         ,
"wiyczzs$$ciwk"                                                          ,
"mfqeu"                                                                  ,
"vXXe1zXX7ftzalmvdmncfivrax@@rjwq"                                       ,
"k$$vtg"                                                                 ,
"exhrtdugemlXXf0"                                                        ,
"behnchkpld"                                                             ,
"mhgxy$$mfcrgXXc5gnp$$$$osqhj"                                           ,
"rlvjy"                                                                  ,
"awe"                                                                    ,
"ctwy"                                                                   ,
"vt"                                                                     ,
"XX54t"                                                                  ,
"zugfmmfomz"                                                             ,
"cv$$cvcvfaadaXX04fsuqjinbfhXXa9cqXXd2c$$d"                              ,
"oj"                                                                     ,
"xazanf$$wbmcrn"                                                         ,
"@@@@zkisyjpbzandqikqjqvee"                                              ,
"dpsnbzdwnxk@@v"                                                         ,
"sj$$tuupr@@oyoh"                                                        ,
"myvkgnwXX81qXXaaokt@@emgejbsyvxcl@@XXee"                                ,
"ejeuqvunjcirdkkpt$$nlns"                                                ,
"twmlvwxyvfyqqzu"                                                        ,
"$$xwtzdpXX98qkcis$$dm@@$$ep$$xyykq"                                     ,
"vvcq@@expok"                                                            ,
"wgukjfanjgpdjb"                                                         ,
"$$mjcjajnxy@@dcpc"                                                      ,
"wdvgnecw@@abXX44klceduzgsvu"                                            ,
"dqtqkukr$$iacngufbqkdpxlwjjt"                                           ,
"$$xj$$XX66qofsqzkoah"                                                   ,
"nptiwwsqdep"                                                            ,
"gsnlxqlXX30mjl"                                                         ,
"yeezwokjwrhelny$$"                                                      ,
"bjauamn@@izpmzqqasid"                                                   ,
"tvjdbkn$$tiziwXX82r"                                                    ,
"w"                                                                      ,
"xwoakbbnjnypnaaXXa9wft$$slrmoqkl"                                       ,
"vwxtnlvaaasyruykgygrvpiopzygf$$vq"                                      ,
"qdancvnvmhlmpj@@isdxs"                                                  ,
"xzc@@elw"                                                               ,
"b$$wxeqvy$$qf$$gXXcaoklsucwicyw$$dovr"                                  ,
"yomlvvjdbngz$$rly$$afr"                                                 ,
"bfb$$x$$aweuwbwmoaXX13$$t$$zhr"                                         ,
"$$dmfoxb$$qvpjzzhyktXXd2$$$$ryhxi"                                      ,
"psqef$$yu@@qiflie$$XX79w"                                               ,
"arzewkej$$lqmh@@sayyusxxo@@"                                            ,
"vuvvp"                                                                  ,
"hc$$lgXX6bcpupsewzklai$$l"                                              ,
"cjdfygc$$auorqybnuqghshXX10"                                            ,
"j"                                                                      ,
"wqjexk$$eyq@@lbroqhk@@dqzsqk"                                           ,
"dws$$ru$$dvxfiwapif$$oqwzmle"                                           ,
"agcykg@@jt@@vzklqjvknoe"                                                ,
"kksd$$jmslja@@z$$y@@bXXaagpyojct"                                       ,
"nnpipxufvbfpoz$$jno"                                                    ,
"dtw"                                                                    ,
"xlolvtahvgqkx@@dgnhj@@spsclpcxv@@"                                      ,
"mxea@@mbjpi"                                                            ,
"lgbotkk$$zmxh@@@@qji$$jszulnjsxkqf"                                     ,
"lwckmhwhx$$gmftlbXX91am"                                                ,
"xxdxqyxth"                                                              ,
"$$lmqhwkjxmvayxy"                                                       ,
"tf"                                                                     ,
"qy"                                                                     ,
"wdqmwxdztax$$m$$XX09XX11xdxmfwxmtqgwvf"                                 ,
"XXcbnazlf$$ghziknszmsrahaf"                                             ,
"eXX6aupmzhxlvwympgjjpdvo$$kylfa"                                        ,
"XX81vhtlillbXXactgoatva"                                                ,
"dvnlgr"                                                                 ,
"f"                                                                      ,
"xgXXfacwizsadgeclm"                                                     ,
"vnnrzbtw$$@@prod@@djbyppngwayy$$"                                       ,
"lrtXXf4jahwvfz"                                                         ,
"aqpnjtom$$ymkak@@dadfybqrso@@fwv"                                       ,
"gz$$aac$$mrbk$$ktommrojraqh"                                            ,
"wycamwoecsftepfnlcdkm"                                                  ,
"nrhddblbuzlqslXX9cben"                                                  ,
"vckxhyqkmqmdseazcykrbysm"                                               ,
"silXXbbtevmt$$gvrvybui$$faw$$j"                                         ,
"cjex@@tpXX45pzf"                                                        ,
"asjobvtxszfodgf$$ibftg"                                                 ,
"gkyjyjdrxdcllnh$$sjcibenrdnxv"                                          ,
"oswsdpjyxpbwnqbcpl$$yrdvs@@zq"                                          ,
"$$$$tyowzc@@fycbp$$jbwrbvgui"                                           ,
"cbpcabqkdgzmpgcwjtrchxp"                                                ,
"iyrzfhXX45gw$$fdlfpiaapXX31xqq"                                         ,
"evgksznidz"                                                             ,
"b@@w@@"                                                                 ,
"loufizbiyXX57aim$$bgk"                                                  ,
"qjfyk"                                                                  ,
"g$$anmloghvgrXX07zwqougqhdz"                                            ,
"usbbmwcxd@@bdgg"                                                        ,
"htitqcpczml"                                                            ,
"eke@@cqvpexqqk$$to$$tqmljrpnXXe6lji$$"                                  ,
"gXXd2ifdsej"                                                            ,
"h$$sk$$haajajpagtcqnzrfqnXXe6btzo"                                      ,
"wfkuffdxlvm@@cvlyzlbyunclhmpp"                                          ,
"myaavh$$spue"                                                           ,
"hqvezXX68d$$eo$$eaioh"                                                  ,
"s$$qd$$oyxxcglcdnuhk"                                                   ,
"ilqvar"                                                                 ,
"srh"                                                                    ,
"puuifxrfmpc$$bvalwiXX2blu@@"                                            ,
"yywlbutufzysbncw@@nqsfbhpz$$mngjq"                                      ,
"zbl@@jfcuop"                                                            ,
"hjdouiragzvxsqkreup@@"                                                  ,
"qi"                                                                     ,
"ckx@@funljXXa7ahi"                                                      ,
"k"                                                                      ,
"ufrcnh$$ajteit"                                                         ,
"cqv$$bgjozjjXX60xXXa8yhvmdvutchjotyuz"                                  ,
"hkuiet$$okuXX8cfhumfpasl"                                               ,
"$$@@sbeXX4d"                                                            ,
"vhknazqt"                                                               ,
"eyyizvzcahgflvmoowvs@@jhvygci"                                          ,
"kkiXX3ewcefkgtjap$$xtpxh$$lzepoqj"                                      ,
"wvtk"                                                                   ,
"$$ynet"                                                                 ,
"zh@@obk$$otagxXX59txfzf"                                                ,
"ocowhxlxXXe6zqgXX63wx@@tclkhq@@vmaze"                                   ,
"w$$cf"                                                                  ,
"qpniprnrzrnvykghqnalr"                                                  ,
"jctcqra$$XX05dhlydpqamorqjsijt@@xjdgt"                                  ,
"sig"                                                                    ,
"qhlbidbflwxe$$xljbwlsXX20vht"                                           ,
"irmrebflaXXefsg$$j"                                                     ,
"nep"                                                                    ,
"hjuvsqlizeqobepf"                                                       ,
"guzbcdp$$obyh"                                                          ,
"$$mjaginsXXf9tqykaxy$$"                                                 ,
"knvsdnmtr$$zervsb"                                                      ,
"hzuy"                                                                   ,
"zza$$k$$buapb@@elmXXfeya"                                               ,
"lrqar$$dfqwkaaqifig$$uixjsz"                                            ,
"$$azuoXX40rmnlhhluwsbbdbXX32pk@@yu$$pbcf"                               ,
"dplkdyty"                                                               ,
"rfoyciebwlwphcycmguc"                                                   ,
"ivnmmiemhgytmlprq@@eh"                                                  ,
"lhkyzaaothfdhmbpsqd@@yyw"                                               ,
"tnlzifupcjcaj"                                                          ,
"@@qiyirsdrfpmu@@XX15xusifaag"                                           ,
"@@lcomf@@s"                                                             ,
"uramjivcirjhqcqcg"                                                      ,
"kkbaklbxfxikffnuhtuXXc6t$$d"                                            ,
"nXXefai"                                                                ,
"$$toy$$bnbpevuzoc$$muywq$$gz$$grbm"                                     ,
"$$muu@@wt"                                                              ,
"@@srby$$ee"                                                             ,
"erf$$gvw$$swfppf"                                                       ,
"pbqcgtn$$iuianhcdazfvmidn@@nslhxdf"                                     ,
"uxbp"                                                                   ,
"up@@mgrcyaegiwmjufn"                                                    ,
"nulscgcewj@@dvoyvhetdegzhs$$"                                           ,
"masv$$k@@rzrb"                                                          ,
"qtxXX79d$$xdxmbxrvhj"                                                   ,
"fid@@otpkgjlh$$qgsvexrckqtnXXf4"                                        ,
"tagzu"                                                                  ,
"bvl@@$$noseec"                                                          ,
"@@xgicuuh"                                                              ,
"w$$a$$npemf"                                                            ,
"sxp"                                                                    ,
"nsmpkticXX8awxftscdcvijjobnq$$gjd"                                      ,
"uks$$$$jxvyvfezz$$aynxoev$$cuoav"                                       ,
"m"                                                                      ,
"lkvokj"                                                                 ,
"vkfam$$yllr$$qXX92oXX4ebecnvhshhqe@@"                                   ,
"efdxcjkjverw"                                                           ,
"lmqzadwhfdgmepXX02tzfcbgrbfekhat"                                       ,
"cpbkXX9azqegbpluczssouopXX36ztpuoxsw"                                   ,
"cqwoczxdd$$erdjka"                                                      ,
"cwvqnjgbw@@fxdlby"                                                      ,
"mvtm"                                                                   ,
"lt$$bbqzpumplkg"                                                        ,
"ntdXXeeuwweucnuuslqfzfq"                                                ,
"yXXabl$$dbebxjrlbmuoo@@XX1au"                                           ,
"qjoqx@@a"                                                               ,
"pu$$ekdnfpmlyXXbago$$"                                                  ,
"fjhhdy"                                                                 ,
"arl"                                                                    ,
"xcywisim$$bwuwf$$$$raepeawwjub"                                         ,
"pbe"                                                                    ,
"dbnqfpzyaumxtqndXXc5dcqrkwyop"                                          ,
"ojvXX40vtkwgkqepmXX8bzft@@vedrry"                                       ,
"wggqkfbwqumsgajqwphjec$$mstxpwz"                                        ,
"zjkbem"                                                                 ,
"icpfqxbelxazlls"                                                        ,
"pvpqs@@abcmtyielugfgcv$$tjxapxqxnx"                                     ,
"oqddwlvmtv$$XX39lyybylfb$$jmngnpjrdw"                                   ,
"gisgbve"                                                                ,
"$$aglg"                                                                 ,
"y$$$$ssXXafvhxlrjv"                                                     ,
"qbgqjsra"                                                               ,
"ihshbjgqpdcljpmdwdprwloy"                                               ,
"djja@@wcdn$$svkrgpqn$$uz$$hcXX43hj"                                     ,
"cbjm"                                                                   ,
"pnn"                                                                    ,
"pqvh$$noh"                                                              ,
"$$@@fdktlp"                                                             ,
"ncea"                                                                   ,
"pqgzphiyy"                                                              ,
"XXbedovhxuipaohlcvkwtxwmpz$$ckaif$$r"                                   ,
"arjuzbjowqciunfwgxtph$$vlhy$$n"                                         ,
"c"                                                                      ,
"nrpdxunulgudqzlhtae"                                                    ,
"iefheu$$uru$$"                                                          ,
"aqijysxuijud$$np@@opbichhudilXXbesum"                                   ,
"pfpevmtstl$$lde$$bzr$$vspdxs"                                           ,
"vparfbdjwvzsocpnzhp"                                                    ,
"gXX4ffxaarafrsjthq@@XXc1rw"                                             ,
"ng@@rqx@@gwpzucbhXXafl"                                                 ,
"rw$$nf@@dna"                                                            ,
"jkkeahxurxla@@gXXb3czrlsyimmwcwthr"                                     ,
"twaailoypu$$oas$$kpuuyedlaw@@XXb0vzt"                                   ,
"hznex@@gdiqvtugi"                                                       ,
"imdibsunjeswhk"                                                         ,
"ta@@icileuzpxro$$cfmv$$mzp"                                             ,
"coykrXX57luiysucfaflmilhlehmvzeiepo"                                    ,
"uXX3dfhXXd4yt"                                                          ,
"piwXX1bz$$eowy$$vfk$$wqiekw"                                            ,
"gan$$y"                                                                 ,
"p$$bevidoazcznr$$hddxuuq$$"                                             ,
"bwzucczznutbxe"                                                         ,
"z$$viqgyqjisior@@iecosmjbknol"                                          ,
"dmlpcglcfkfsctxydjvayhymvXX3c@@gp"                                      ,
"bfvkqrintbbvgfv"                                                        ,
"xlzntrgdck$$cprcXXadczyarbznqmuhxyuh"                                   ,
"uqdxnuwioc$$kdytxq@@ig"                                                 ,
"xrafmucpmfi"                                                            ,
"vr$$hltmfrge"                                                           ,
"eonf$$nt@@wtcnsocs"                                                     ,
"jXXb7xoslyjeyjksplkqixncgkylkw"                                         ,
"njw$$pefgfbezXX9axshdmplxzquqe"                                         ,
"diXX58bvptfsafirpc"                                                     ,
"lXX1fkco"                                                               ,
"x"                                                                      ,
"mprndo$$n"                                                              ,
"psegit"                                                                 ,
"svbdnkkuuqs$$sqxu$$oqcyz$$aizashk"                                      ,
"cwkljukxer@@$$@@nff$$esjwiyaoy"                                         ,
"ilxrkgbjjxpvhdtq$$cpiuoofdnkpp"                                         ,
"hlngi$$ulxep@@qohtmqnqjb$$rkgerho"                                      ,
"gxws$$bcgm$$p"                                                          ,
"bv$$mds@@zhfusiepgrz@@bXX32fscdzz"                                      ,
"lXXfampwtmeXX69qvxnx$$$$XXc4jruuymjxrpsv"                               ,
"qqmxhrn"                                                                ,
"xziq@@XX18ybyvXX9am$$neacoqjzytertisysza"                               ,
"aqcbvlvcrzceeyx@@j$$$$x"                                                ,
"yjuhhb"                                                                 ,
"XX5em$$squulpy"                                                         ,
"dpbntplgmwb"                                                            ,
"utsgfkm@@vbftjknlktpthoeo"                                              ,
"ccxjgiocmuhf$$ycnh"                                                     ,
"lltj$$kbbxi"
];
// Sorry, but I'll use find/replace tools from Notepad for that one !
// XX : \x (XX plus 2 next characters count for one.)
// @@, \\ : counts for one character


function conclusion_8_1() {
	var answer = 0;
	var i;
	var c;
	notRawData.forEach(str => {
		i = 0;
		answer += 2; // Both quotes 
		while (i < str.length) {
			c = str.charAt(i);
			if (c == '@' || c == '$') {
				answer++;
				i+=2;
			} else if (c == 'X') {
				answer+=3; // 4 characters, but one at the end
				i+=2;
			} else {
				i++;
			}
			
		}
	});
	
	return answer;
}

function conclusion_8_2() {
	var answer = 0;
	var i;
	var c;
	notRawData.forEach(str => {
		i = 0;
		answer += 4; // Add two ( \" )s
		while (i < str.length) {
			c = str.charAt(i);
			if (c == '@' || c == '$') {
				answer+=2;
				i+=2; //     \\ becomes \\\\ and \" becomes \\\" 
			} else if (c == 'X') {
				answer++; //     \x123 becomes \\x123
				i+=2;
			} else {
				i++;
			}
			
		}
	});
	
	return answer;
}

